travis:
  secure:
    BINSTAR_TOKEN: nqNVmyZy9lkMQQNekLWFjngNKcnNBFfb+nBtXVsJc2d4Lsg+0FbtbL7fg9gM8i887P2Zo8n4gwAUlitQ4gjrSqbT5nCIBHGr+ICS0RTSXP7BY4Hgf35DXKDZdl4mOeD7b1ezSvslv2guxAyM5tA8MR7AEtswYmU1Hj8EAT1wLlq71Q/c/cQC7HHk5o4tRUeLr1cT0dJ9PLtTuRpxm0cDWjvmoP/3mi2puB0nSC1kUh2IwknAhKCnqhZrFsgwwxAxLVYuuf6SsblPLOPAtWx+2ehvgS1XrXrrPIMcmY4wmaRzI4TjxKAHDjaJSBQofJr9iNAhksQDkFRE6NfxkWhWtVCeCoP/wqKp6qx/pOn0c+QEjfJUKDKXV9SgWeLNME2iseLV97uTCEC7bc8J1z4zYHrtbQNAEIqyNJOHZk9jeFxS7AenIRbbX7O2deS/rYewvqR/w1A3HOGATwCKKOsSnwvqcOBNe/RdQfxgIEYxFtuq7CPkqhDi7aKc3QNXkg0ZbZvwZ/JwFxeuXMdFFJAYYcLonJA/aqf7o40JTptWPNAx5zE0P+VkfG2Y6G5iJC0fBf7OmwiwrNB6hLGWNvcrmcoA5pOqfT5nL6/7PAeDwh/U8n4dT/uRZqvSlV8+Csiuax9OH58ogTQAsmQAGfHhRMEeXvxdDKDOkIWRETrZBBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
