travis:
  secure:
    BINSTAR_TOKEN: mm+VnO9smMsZYJzFXuDqjFL+yAUJOvJzjgKzT4sywPDFOyl5Mv+EseeaQBPaHgl4fSVe4hGn/TDsDtXyAGj5gPtOSoVcgAEQhR/ZCXfYjcMz5dnWfMNi7YpzW2koy0IIB7AO2s8he80fTqUZnd64rFlZwV3gqMkiKbU8W60JVIQLZ+nK9c1biqyCY6wJj0kri8SyOB1zV8/JKl+SRfJv+EfzBhvbRaIRuCFXs45Vm/iEm+f5VPJA0HIsIRFsUvuwFD1D0IdZIVkjgyTNs7tSl1H85Rp6ASqfTRY9zEC2i9E1i5RtlQ6uLdJZ945vyfNtfdwQ2wqAWggqQvfXkuY/EG1GxXfuouOMbFDsgYJm7JMzDJkoo3mPjMDG2kJaXK0Gg25ewjNf4Kc80AGNzmKD81WA9NNpRlCfcWhHeZDpkYIv8r/c5SQRi6bAR+ryps7Audmbw2DHHF8AGn1CEqmg8s+fLq8VAp4TRnbVmCqJYppYk0EYE8x4UyRkdA0pff8qVKHsgTKvh+LlsCJ9yV9W4XuPnqFwSpyUWG0pF9q2Ft7P6xfLcHpcvT9zsxVqWllcHO/yiYfAWS9lDfd09YNWbp0QEl8RqSwD2VcajL4ulBDNmraaf+kcgjJ3LuG1SC0bELUf3zP1Z3pm+uCbuW24nWArcdkjaEES7jzwXeJPn6c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
